In [1]:
import pandas as pd
import numpy as np

## data preprocessing

###### check point: raw_data

In [2]:
raw_data=pd.read_csv('Absenteeism-data.csv')

In [3]:
raw_data.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

###### check point: df

In [4]:
df = raw_data.copy()

In [5]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [6]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [8]:
df=df.drop(['ID'],axis=1)

###### dummy variable 'reason for absence'

In [9]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)

In [10]:
reason_columns.head()

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0  
2   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0  
4   0   0   1   0   0   0   0   0

In [11]:
df = df.drop(['Reason for Absence'], axis = 1)

###### group 'reason for absence'

In [12]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [13]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)

In [14]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [15]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [16]:
df.columns = column_names

In [17]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [18]:
df = df[column_names_reordered]

In [19]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

###### check point: df_reason_mod

In [20]:
df_reason_mod = df.copy()

###### extract the month value

In [21]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [22]:
list_months = []
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [23]:
df_reason_mod['Month Value'] = list_months

###### extract the weekday value

In [24]:
def date_to_weekday(date_value):
    return date_value.weekday()
df_reason_mod['Day of the Week']=df_reason_mod['Date'].apply(date_to_weekday)

In [25]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [26]:
df_reason_mod = df_reason_mod.drop(['Date'], axis = 1)

In [27]:
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week'], dtype=object)

In [28]:
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

In [29]:
df_reason_mod = df_reason_mod[column_names_upd]
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

###### check point: df_reason_date_mod

In [30]:
df_reason_date_mod = df_reason_mod.copy()
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

###### education, children, pets

In [31]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [32]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [33]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [34]:
df_reason_date_mod['Education'].unique()

array([0, 1], dtype=int64)

In [35]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

###### check point: df_preprocessed

In [36]:
df_preprocessed = df_reason_date_mod.copy()
df_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1            7                4   
6         0         0         0         1            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            7                0   
9         0         0         0         1            7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2  
6               27          0         1     4                          8  
7               23          0         4     0                          4  
8               25          0         2     0                         40  
9               29          1         1     1                          8

## logistic regression

###### creat the target

In [37]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [38]:
targets = np.where(df_preprocessed['Absenteeism Time in Hours'] > 
                   df_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [39]:
df_preprocessed['Excessive Absenteeism'] = targets

In [40]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [41]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [42]:
df_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

###### inputs

In [43]:
df_with_targets.shape

(700, 15)

In [44]:
unscaled_inputs = df_with_targets.iloc[:,:-1]

In [45]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

###### standardize the inputs

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
absenteeism_scaler = StandardScaler()

In [48]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [49]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [50]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [51]:
scaled_inputs.shape

(700, 14)

###### Split the data into train & test and shuffle

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [54]:
print (x_train.shape, y_train.shape)

(560, 14) (560,)


In [55]:
print (x_test.shape, y_test.shape)

(140, 14) (140,)


##### Logistic regression with sklearn

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [57]:
reg = LogisticRegression()

In [58]:
reg.fit(x_train,y_train)

LogisticRegression()

In [59]:
reg.score(x_train,y_train)

0.7839285714285714

##### Manually check the accuracy

In [60]:
model_outputs = reg.predict(x_train)

In [61]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

##### Finding the intercept and coefficients

In [62]:
reg.intercept_

array([-0.22206736])

In [63]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [64]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [65]:
feature_name = unscaled_inputs.columns.values

In [66]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4               Month Value     0.187937
5           Day of the Week    -0.070623
6    Transportation Expense     0.706393
7          Distance to Work    -0.039868
8                       Age    -0.200895
9   Daily Work Load Average    -0.004564
10          Body Mass Index     0.319336
11                Education    -0.135508
12                 Children     0.381724
13                     Pets    -0.333243

In [67]:
summary_table.index = summary_table.index + 1

In [68]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [69]:
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5               Month Value     0.187937
6           Day of the Week    -0.070623
7    Transportation Expense     0.706393
8          Distance to Work    -0.039868
9                       Age    -0.200895
10  Daily Work Load Average    -0.004564
11          Body Mass Index     0.319336
12                Education    -0.135508
13                 Children     0.381724
14                     Pets    -0.333243

In [70]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [71]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.222067    0.800861
1                  Reason_1     2.076018    7.972656
2                  Reason_2     0.335048    1.398007
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5               Month Value     0.187937    1.206757
6           Day of the Week    -0.070623    0.931814
7    Transportation Expense     0.706393    2.026668
8          Distance to Work    -0.039868    0.960916
9                       Age    -0.200895    0.817998
10  Daily Work Load Average    -0.004564    0.995447
11          Body Mass Index     0.319336    1.376213
12                Education    -0.135508    0.873272
13                 Children     0.381724    1.464808
14                     Pets    -0.333243    0.716596

In [72]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.076018    7.972656
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
7    Transportation Expense     0.706393    2.026668
13                 Children     0.381724    1.464808
2                  Reason_2     0.335048    1.398007
11          Body Mass Index     0.319336    1.376213
5               Month Value     0.187937    1.206757
10  Daily Work Load Average    -0.004564    0.995447
8          Distance to Work    -0.039868    0.960916
6           Day of the Week    -0.070623    0.931814
12                Education    -0.135508    0.873272
9                       Age    -0.200895    0.817998
0                 Intercept    -0.222067    0.800861
14                     Pets    -0.333243    0.716596

## testing the model

In [73]:
reg.score(x_test,y_test)

0.7357142857142858

In [74]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73864865, 0.26135135],
       [0.58845661, 0.41154339],
       [0.36763564, 0.63236436],
       [0.81198089, 0.18801911],
       [0.0613996 , 0.9386004 ],
       [0.30742403, 0.69257597],
       [0.29538175, 0.70461825],
       [0.08106026, 0.91893974],
       [0.80435611, 0.19564389],
       [0.76038732, 0.23961268],
       [0.46271934, 0.53728066],
       [0.15484755, 0.84515245],
       [0.04619732, 0.95380268],
       [0.72991038, 0.27008962],
       [0.23140393, 0.76859607],
       [0.55130442, 0.44869558],
       [0.5292476 , 0.4707524 ],
       [0.55522744, 0.44477256],
       [0.38197963, 0.61802037],
       [0.02527634, 0.97472366],
       [0.69617984, 0.30382016],
       [0.80458387, 0.19541613],
       [0.37734902, 0.62265098],
       [0.40003074, 0.59996926],
       [0.18229161, 0.81770839],
       [0.76011784, 0.23988216],
       [0.47050402, 0.52949598],
       [0.88997625, 0.11002375],
       [0.13577639, 0.86422361],
       [0.7969686 , 0.2030314 ],
       [0.

In [75]:
predicted_proba.shape

(140, 2)

In [76]:
predicted_proba[:,1]

array([0.26135135, 0.41154339, 0.63236436, 0.18801911, 0.9386004 ,
       0.69257597, 0.70461825, 0.91893974, 0.19564389, 0.23961268,
       0.53728066, 0.84515245, 0.95380268, 0.27008962, 0.76859607,
       0.44869558, 0.4707524 , 0.44477256, 0.61802037, 0.97472366,
       0.30382016, 0.19541613, 0.62265098, 0.59996926, 0.81770839,
       0.23988216, 0.52949598, 0.11002375, 0.86422361, 0.2030314 ,
       0.38454827, 0.70459151, 0.70138178, 0.56363893, 0.19541613,
       0.54256241, 0.20504956, 0.82072323, 0.44466019, 0.61108219,
       0.20908782, 0.40281153, 0.21373621, 0.09844091, 0.84224496,
       0.66612989, 0.71672931, 0.26982044, 0.20155736, 0.17070043,
       0.5733945 , 0.08298962, 0.67931742, 0.28630329, 0.87253409,
       0.48546569, 0.9325331 , 0.2462249 , 0.08169672, 0.08239341,
       0.72795552, 0.6695154 , 0.31201864, 0.86026294, 0.1838827 ,
       0.2596655 , 0.0131662 , 0.22029913, 0.8123649 , 0.31453865,
       0.20433741, 0.07128014, 0.93325923, 0.46319471, 0.65517

## save the model

In [77]:
import pickle

In [78]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [79]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)